language: node_js

node_js: "12.18.1"

cache:
  directories:
    - node_modules

install:
  - npm i

script:
  - npm run build:lib
  - npm run build:doc -- --base-href=${BASE_HREF}

after_script:
  - cd dist/doc
  - git init
  - git checkout -b ${GH_BRANCH}
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "release docs" --no-verify
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" ${GH_BRANCH}:${GH_BRANCH}

branches:
  only:
    - master
